Repository opencloud-eu/reva, pull requests merged in 2025-03, with the labels that each got.

#101 feat: add ready release go
  .woodpecker/release.yaml
  release-config.ts
Labels: Type:Documentation

#106 Fix traversing thrash items
  .github/workflows/changelog.yml
  .github/workflows/docker.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  pkg/storage/fs/posix/trashbin/trashbin.go
Labels: Type:Bug

#113 Properly support disabling versioning
  pkg/storage/fs/posix/posix.go
Labels: Type:Bug

#114 Replace revisions with the exact same mtime
  pkg/storage/fs/posix/tree/revisions.go
  pkg/storage/pkg/decomposedfs/tree/revisions.go
Labels: Type:Bug

#112 New "jsoncs3" backend for app token storage
  go.mod
  go.sum
  pkg/appauth/manager/jsoncs3/jsoncs3.go
  pkg/appauth/manager/jsoncs3/jsoncs3_suite_test.go
  pkg/appauth/manager/jsoncs3/jsoncs3_test.go
  pkg/appauth/manager/loader/loader.go
Labels: Type:Enhancement

#119 appauth/jsoncs3: Allow deletion using password hash
  pkg/appauth/manager/jsoncs3/jsoncs3.go
  pkg/appauth/manager/jsoncs3/jsoncs3_test.go
Labels: Type:Bug

#120 Keep metadata lock files in .oc-nodes
  pkg/storage/fs/posix/lookup/lookup.go
  pkg/storage/fs/posix/posix.go
  pkg/storage/fs/posix/testhelpers/helpers.go
  pkg/storage/fs/posix/tree/tree.go
  pkg/storage/pkg/decomposedfs/metadata/hybrid_backend.go
  pkg/storage/pkg/decomposedfs/metadata/messagepack_backend.go
  pkg/storage/pkg/decomposedfs/metadata/xattrs_backend.go
Labels: Type:Bug

#125 Fix moving lockfiles during moves
  pkg/storage/fs/posix/tree/tree.go
Labels: Type:Bug

#139 fix(appauth/jsoncs3) Avoid returing password hashes on API
  pkg/appauth/manager/jsoncs3/jsoncs3.go
  pkg/appauth/manager/jsoncs3/jsoncs3_test.go
Labels: Type:Bug

#141 Always try to get the blob id/size from the metadata
  pkg/storage/pkg/decomposedfs/node/node.go
Labels: Type:Bug

#146 enhancement(tus): Improve zerolog wrapper for slog
  pkg/rhttp/datatx/manager/tus/tus.go
Labels: Type:Enhancement
