Repository opencloud-eu/reva, pull requests merged in 2025-05, with the labels that each got.

#202 Abort when the space root has already been created. port #199 to stable
  pkg/storage/pkg/decomposedfs/spaces.go
Labels: Type:Bug

#210 Add ParentID to events so it's available to the consumer
  pkg/events/files.go
  pkg/events/postprocessing.go
  pkg/storage/fs/posix/tree/assimilation.go
  pkg/storage/pkg/decomposedfs/decomposedfs.go
Labels: Type:Enhancement

#217 ldapclient: Add Password Modify implementation
  pkg/utils/ldap/reconnect.go
Labels: Type:Maintenance
