Repository opencloud-eu/reva, pull requests merged in 2025-08, with the labels that each got.

#292 Only scan dirty directories when recursing
  pkg/storage/fs/posix/tree/assimilation.go
Labels: Type:Bug

#297 Filter users by tenant id
  examples/plugin/json/json.go
  internal/grpc/services/userprovider/userprovider.go
  pkg/cbox/user/rest/rest.go
  pkg/user/manager/demo/demo.go
  pkg/user/manager/demo/demo_test.go
  pkg/user/manager/json/json.go
  pkg/user/manager/json/json_test.go
  pkg/user/manager/ldap/ldap.go
  pkg/user/manager/memory/memory.go
  pkg/user/manager/memory/memory_test.go
  pkg/user/manager/nextcloud/nextcloud.go
  pkg/user/manager/nextcloud/nextcloud_test.go
  pkg/user/manager/owncloudsql/owncloudsql.go
  pkg/user/rpc_user.go
  pkg/user/user.go
  pkg/utils/ldap/identity.go
  tests/integration/grpc/fixtures/ldap/20_users.ldif
  tests/integration/grpc/fixtures/users.demo.json
  tests/integration/grpc/userprovider_test.go
Labels: Type:Enhancement

#305 Only send TrashbinPurged if there is no key
  internal/grpc/interceptors/eventsmiddleware/events.go
Labels: Type:Bug

#310 fix(posixfs): Ignore Events for Spaceroots
  pkg/storage/fs/posix/tree/assimilation.go
  pkg/storage/fs/posix/tree/tree.go
Labels: Type:Bug

#317 add UserSoftDelete events
  pkg/events/users.go
Labels: Type:Feature
