Repository opencloud-eu/reva, pull requests merged in 2025-04, with the labels that each got.

#149 Cache internal path and disabled flag
  pkg/storage/fs/posix/trashbin/trashbin.go
  pkg/storage/pkg/decomposedfs/node/node.go
Labels: Type:Enhancement

#150 Fix move races
  pkg/storage/fs/posix/lookup/store_idcache.go
  pkg/storage/fs/posix/options/options.go
  pkg/storage/fs/posix/tree/assimilation.go
  pkg/storage/fs/posix/tree/tree.go
Labels: Type:Bug

#152 Fix handling collaborative moves
  pkg/storage/fs/posix/lookup/lookup.go
  pkg/storage/fs/posix/lookup/store_idcache.go
  pkg/storage/fs/posix/lookup/store_idcache_test.go
  pkg/storage/fs/posix/trashbin/trashbin.go
  pkg/storage/fs/posix/tree/assimilation.go
  pkg/storage/pkg/decomposedfs/metadata/hybrid_backend.go
  pkg/storage/pkg/decomposedfs/metadata/messagepack_backend.go
  pkg/storage/pkg/decomposedfs/metadata/metadata.go
  pkg/storage/pkg/decomposedfs/metadata/xattrs_backend.go
  pkg/storage/pkg/decomposedfs/node/node.go
Labels: Type:Bug

#155 Periodically log stats about inotify resources usage on the system
  pkg/storage/fs/posix/options/options.go
  pkg/storage/fs/posix/tree/inotifywatcher.go
  pkg/storage/fs/posix/tree/inotifywatcher_default.go
  pkg/storage/fs/posix/tree/tree.go
Labels: Type:Enhancement

#158 Fix race condition when moving/restoring items in quick succession
  pkg/storage/fs/posix/tree/assimilation.go
Labels: Type:Bug

#161 flush cache by age
  .woodpecker/purge-cache.yaml
Labels: Type:DevOps

#165 Do not send "delete" sses when items are moved
  pkg/storage/fs/posix/tree/assimilation.go
Labels: Type:Bug

#166 Fix stale file metadata cache entries
  pkg/storage/fs/posix/trashbin/trashbin.go
Labels: Type:Bug

#167 revert: remove "edition" property
  internal/http/services/owncloud/ocdav/config/config.go
  internal/http/services/owncloud/ocdav/status.go
  internal/http/services/owncloud/ocs/handlers/cloud/capabilities/capabilities.go
  pkg/micro/ocdav/option.go
  pkg/owncloud/ocs/capabilities.go
Labels: Type:Feature

#172 Fix wrong blobsize attributes due to premature assimilation
  pkg/storage/pkg/decomposedfs/upload/upload.go
Labels: Type:Bug

#176 Improve performance and stabiity of assimilation
  pkg/storage/fs/posix/tree/assimilation.go
  pkg/storage/fs/posix/tree/tree_test.go
Labels: Type:Bug

#178 Fix space ids getting overwritten
  .mockery.yaml
  pkg/storage/fs/posix/lookup/lookup.go
  pkg/storage/fs/posix/lookup/lookup_test.go
  pkg/storage/fs/posix/lookup/mocks/IDCache.go
  pkg/storage/pkg/decomposedfs/metadata/hybrid_backend.go
Labels: Type:Bug

#181 ci: make release plugin compatible with stable branch workflow
  release-config.ts
Labels: Type:DevOps

#179 Backport spaceid fix
  .mockery.yaml
  pkg/storage/fs/posix/lookup/lookup.go
  pkg/storage/fs/posix/lookup/lookup_test.go
  pkg/storage/fs/posix/lookup/mocks/IDCache.go
  pkg/storage/pkg/decomposedfs/metadata/hybrid_backend.go
Labels: Type:Bug

#180 Cephfs
  pkg/storage/fs/posix/options/options.go
  pkg/storage/fs/posix/tree/cephfswatcher.go
  pkg/storage/fs/posix/tree/gpfswatchfolderwatcher.go
  pkg/storage/fs/posix/tree/tree.go
Labels: Type:Enhancement

#188 ocdav: Fix check for empty request body
  internal/http/services/owncloud/ocdav/copy.go
  internal/http/services/owncloud/ocdav/delete.go
  internal/http/services/owncloud/ocdav/mkcol.go
  internal/http/services/owncloud/ocdav/move.go
  internal/http/services/owncloud/ocdav/ocdav.go
Labels: Type:Bug

#196 Do not choke when one of the directory entries can't be read
  pkg/storage/fs/posix/tree/tree.go
Labels: Type:Bug

#199 Abort when the space root has already been created.
  pkg/storage/pkg/decomposedfs/spaces.go
Labels: Type:Bug
